name: Levely

services:
  db:
    image: postgres:18
    container_name: levely-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - levely-network

networks:
  levely-network:
    driver: bridge
